# Generated by Django 3.2.6 on 2021-09-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preco')),
                ('categoria', models.CharField(max_length=15, verbose_name='categoria')),
                ('descricao', models.TextField(max_length=150, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], max_length=40, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Preco',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
