# Generated by Django 3.2.6 on 2021-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='descricao',
            field=models.TextField(choices=[('a', 'Premium'), ('b', 'Pro'), ('c', 'Plus')], max_length=150, verbose_name='Descrição'),
        ),
    ]
