# Generated by Django 3.2.6 on 2021-09-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210905_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='categoria',
            field=models.CharField(choices=[('Premium', 'C'), ('Pro', 'B'), ('Plus', 'A')], max_length=15, verbose_name='categoria'),
        ),
    ]
