# Generated by Django 3.2.6 on 2021-09-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
