# Generated by Django 3.2.6 on 2021-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preco'),
        ),
    ]
